name: Baris
favicon: null
layout_spectrum: 0.8
title: "Baris' Grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a4566'
    - '#1a1f23'
    - '#69788d'
    - '#ecb28e'
    - '#74493c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: 5a6da832-8f01-4034-824c-c024d4c0912f
    url: null
